# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dev.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dev.yml down`

#TODO

version: "3"
services:

  behave_db:
    build: ./
    image: behave_db.dev
    user: behave_db
    container_name: behave_db
    stdin_open: true
    depends_on:
      - python2.7
      - python3.8
    volumes:
      - ./tests:/app/tests
      - ./var/log:/app/var/log
